---
version: '3.6'
services:
  # External dependencies
  redis:
    image: redis:alpine
    restart: always
  antispam-redis:
    image: redis:alpine
    restart: always
  # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.7}
    restart: always
  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.7}
    restart: always
    networks: {default: {ipv4_address: 192.168.203.254}}
  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.7}
    restart: always
    depends_on: [redis]
  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.7}
    restart: always
    depends_on: [front]
  smtp:
    image: corpusops/mailu-postfix:${MAILU_VERSION:-1.7}
    restart: always
    depends_on: [front, resolver]
  antispam: &antispam
    image: corpusops/mailu-rspamd:${MAILU_VERSION:-1.7}
    restart: always
    depends_on: [front, resolver]
  antispam-feeder:
    <<: [ *antispam ]
  antivirus:
  # Optional services
  antivirus:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-1.7}
    restart: always
    depends_on: [resolver]
  # Webmail
  webmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rainloop:${MAILU_VERSION:-1.7}
    restart: always
    depends_on: [imap]
  database:
    image: "corpusops/postgres:12"
    restart: always
networks:
  default:
    driver: bridge
    ipam:
      driver: default
