---
ssh_envs:
  vars:
    sudo_flags: "-HE"
    ansible_port: 22
    ansible_user: root
    ansible_ssh_common_args: "-i {{cops_deploy_ssh_key_paths['deploy'].path}} -p {{ansible_port}} -o IdentitiesOnly=yes"
  hosts:
    mailer.example.com:
      ansible_port: "22"
prod:
  hosts:
    mailer.example.com:
mailer_servers:
  children:
    prod:
mailer_servers: {children: {mailer_servers: null}}
app_servers: {children: {mailer_servers: null}}
mailer:
  children:
    controller:
    app_servers:
mailer:
  children:
    mailer:
controller: {hosts: {localhost: {ansible_connection: local}}}
