---
cops_mailer_name: mailerinstance
cops_mailer_deploy_env: "dev"
cops_mailer_dir: "/srv/docker/{{cops_mailer_name}}"
cops_mailer_project_module_name: "{{cops_mailer_name}}"
cops_mailer_composename: "{{cops_mailer_name}}"
cops_mailer_tld_domain: example.com
cops_mailer_mail_domain: "antispam.{{ cops_mailer_tld_domain }}"
cops_mailer_hostname: "mx.{{cops_mailer_mail_domain}}"
cops_mailer_ourdomains_default: "({{cops_mailer_mail_domain}}|{{cops_mailer_tld_domain}}|{{cops_mailer_hostname}})"
cops_mailer_ourdomains: "{{cops_mailer_ourdomains_default}}"
cops_mailer_rspamdourdomains: "{{cops_mailer_ourdomains_default}}"
cops_mailer_alternate_hostnames: [".{{cops_mailer_tld_domain}}"]
cops_mailer_db_password: "secret4gzQNe3c8851VOJ"
cops_mailer_db_name: "{{cops_mailer_name}}"
cops_mailer_build_args: ""
# backup could be remove in a-while when we have redeployed it everywhere
cops_mailer_restarted_services_default: "database redis antispam-redis resolver imap smtp-configure-source-ip smtp antispam antivirus webmail admin front antispam-feeder"
cops_mailer_restarted_services: "{{cops_mailer_restarted_services_default}}"
cops_mailer_purge_volumes: []
cops_mailer_sshargs: >-
  {% set k = hostvars[inventory_hostname].get(
                'ansible_ssh_private_key_file', '') %}
  {% if k%}-o IdentityFile={{k}} -o IdentitiesOnly=yes{%endif%}
  {% if (
      hostvars[inventory_hostname].ansible_connection|default('ssh')
     ) not in [ 'smart', 'local'] %}
  {{ hostvars[inventory_hostname].ssh_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_common_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_extra_args | default('') }}
  {% endif %}
cops_mailer_build: false
cops_mailer_pull: true
cops_mailer_registries: []
cops_mailer_rspamd_password: mailu
#- {registry: registry.foo.net, username: foo, password: bar}
cops_mailer_compose_files: [docker-compose.yml, docker-compose-prod.yml, docker-compose-prod-overrides.yml]
cops_mailer_dc:
  docker-compose {% for i in cops_mailer_compose_files %} -f {{i}}{% endfor %}
  -p "{{cops_mailer_composename}}"
cops_mailer_docker_env_freeform: |-
  {{ cops_mailer_docker_env_defaults}}
  {{ cops_mailer_docker_env_extra}}
cops_mailer_docker_env_defaults: |-
  # Mailu main configuration file
  #
  # Generated for compose flavor
  #
  # This file is autogenerated by the configuration management wizard.
  # For a detailed list of configuration variables, see the documentation at
  # https://mailu.io
  DCRON_ARGS=-b -l 3 -S -f
  ###################################
  # Common configuration variables
  ###################################
  MAILU_VERSION={{cops_mailer_mailu_version}}
  VERSION={{cops_mailer_mailu_version}}
  # Set this to the path where Mailu data and configuration is stored
  # This variable is now set directly in `docker-compose.yml by the setup utility
  # ROOT=/mailu
  # Mailu version to run (1.0, 1.1, etc. or master)
  # Set to a randomly generated 16 bytes string
  SECRET_KEY={{cops_mailer_secret_key}}
  # Address where listening ports should bind
  # This variables are now set directly in `docker-compose.yml by the setup utility
  # PUBLIC_IPV4= 127.0.0.1 (default: 127.0.0.1)
  # PUBLIC_IPV6= ::1 (default: ::1)
  # Subnet of the docker network. This should not conflict with any networks to which your system is connected. (Internal and external!)
  RSPAMD_PASSWORD={{cops_mailer_rspamd_password}}
  SUBNET={{cops_mailer_subnetp}}
  OUTIP={{cops_mailer_out_ip}}
  # Main mail domain
  DOMAIN={{cops_mailer_mail_domain}}
  # Hostnames for this server, separated with comas
  HOSTNAMES={{cops_mailer_mail_domain}},{{cops_mailer_hostname}}
  # Postmaster local part (will append the main mail domain)
  POSTMASTER={{cops_mailer_postmaster}}
  # Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
  TLS_FLAVOR={{cops_mailer_tls_flavor}}
  # Authentication rate limit (per source IP address)
  AUTH_RATELIMIT={{cops_mailer_ratelimit}}
  # Opt-out of statistics, replace with "True" to opt out
  DISABLE_STATISTICS={{cops_mailer_disable_statistics}}
  ###################################
  # Optional features
  ###################################
  # Expose the admin interface (value: true, false)
  ADMIN={{cops_mailer_enable_admin}}
  # Choose which webmail to run if any (values: roundcube, rainloop, none)
  WEBMAIL={{cops_mailer_webmail}}
  # Dav server implementation (value: radicale, none)
  WEBDAV={{cops_mailer_dav}}
  # Antivirus solution (value: clamav, none)
  ANTIVIRUS={{cops_mailer_antivirus}}
  #Antispam solution
  ANTISPAM=none
  ###################################
  # Mail settings
  ###################################
  # Message size limit in bytes
  # Default: accept messages up to 50MB
  # Max attachment size will be 33% smaller
  MESSAGE_SIZE_LIMIT={{cops_mailer_message_size_limit}}
  # Networks granted relay permissions
  # Use this with care, all hosts in this networks will be able to send mail without authentication!
  RELAYNETS={{cops_mailer_relaynets}}
  # Will relay all outgoing mails if configured
  RELAYHOST={{cops_mailer_relayhost}}
  # Fetchmail delay
  FETCHMAIL_DELAY=600
  # Recipient delimiter, character used to delimiter localpart from custom address part
  RECIPIENT_DELIMITER=+
  # DMARC rua and ruf email
  DMARC_RUA={{cops_mailer_dmarc_rua}}
  DMARC_RUF={{cops_mailer_dmarc_ruf}}
  # Welcome email, enable and set a topic and body if you wish to send welcome
  # emails to all users.
  WELCOME=false
  WELCOME_SUBJECT=Welcome to your new email account
  WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!
  # Maildir Compression
  # choose compression-method, default: none (value: bz2, gz)
  COMPRESSION=
  # change compression-level, default: 6 (value: 1-9)
  COMPRESSION_LEVEL=
  ###################################
  # Web settings
  ###################################
  # Path to redirect / to
  WEBROOT_REDIRECT=/webmail
  # Path to the admin interface if enabled
  WEB_ADMIN=/admin
  # Path to the webmail if enabled
  WEB_WEBMAIL=/webmail
  # Website name
  SITENAME={{cops_mailer_sitename}}
  # Linked Website URL
  WEBSITE={{cops_mailer_website}}
  ###################################
  # Advanced settings
  ###################################

  # Log driver for front service. Possible values:
  # json-file (default)
  # journald (On systemd platforms, useful for Fail2Ban integration)
  # syslog (Non systemd platforms, Fail2Ban integration. Disables `docker-compose log` for front!)
  # LOG_DRIVER=json-file

  # Docker-compose project name, this will prepended to containers names.
  COMPOSE_PROJECT_NAME={{cops_mailer_composename}}
  # Default password scheme used for newly created accounts and changed passwords
  # (value: BLF-CRYPT, SHA512-CRYPT, SHA256-CRYPT, MD5-CRYPT, CRYPT)
  PASSWORD_SCHEME=BLF-CRYPT
  # Header to take the real ip from
  REAL_IP_HEADER={{cops_mailer_real_ip_header}}
  # IPs for nginx set_real_ip_from (CIDR list separated by commas)
  REAL_IP_FROM={{cops_mailer_real_ip_from}}
  # choose wether mailu bounces (no) or rejects (yes) mail when recipient is unknown (value: yes, no)
  REJECT_UNLISTED_RECIPIENT={{cops_mailer_reject_unlisted_recipient}}
  # Log level threshold in start.py (value: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET)
  LOG_LEVEL={{cops_mailer_log_level}}
  ###################################
  # Database settings
  ###################################
  DB_FLAVOR=postgresql
  DB_PW={{cops_mailer_db_password}}
  ###################################
  # Extra settings
  ###################################
  # SPAM
  SPAMCOLLECT_USER={{cops_mailer_spamcollect_user}}
  SPAMCOLLECT_HOST={{cops_mailer_spamcollect_host}}
  SPAMCOLLECT_SCRIPT={{cops_mailer_spamcollect_script}}
  SPAMCOLLECT_PATH={{cops_mailer_spamcollect_path}}
  SPAMS_FOLDER=/spamfolder/spamf/verified_spam
  HAMS_FOLDER=/spamfolder/spamf/verified_ham
  # SMTP CCONTAINER CONFIGURATION
  MAILLOGSIZE={{cops_mailer_maillogsize}}
  MAILLOGS_KEEP={{cops_mailer_maillogs_keep}}
  HOST_ANTISPAM_CLIENT=antispam:11334
  SPAMLEARN_MINUTES={{cops_mailer_spamlearn_minutes}}
  SPAMLEARN_PERIODICITY={{cops_mailer_spamlearn_periodicity}}
  SPAM_SKIP_GET={{cops_mailer_spam_skip_get}}
# set to 1 if you have no spam/ham source to get stuff from
cops_mailer_spam_skip_get: ""
# free form for params inside dockerenv
cops_mailer_dotenv: |-
  # nothing
cops_mailer_dotenv_extra: ""
# free form for params inside dockerenv
cops_mailer_docker_env_extra: ""
# free form for params inside local.py
cops_mailer_localpy_extra: ""
# Normally playbook is in ./.ansible/playbooks
cops_mailer_code_dir: "{{playbook_dir}}/../.."
cops_mailer_code_rsync_opts: [
    "-azv",
    # include deploy projects base code
    "--include", "local/*-deploy",
    "--exclude", ".ansible",
    "--exclude", "local/*",
    "--exclude", "overrides",
    "--exclude", ".git",
    "--exclude", ".tox",
    "--exclude", ".env",
    "--exclude", "docker.env"]
cops_mailer_log_level: WARNING
cops_mailer_spamcollect_script: /root/spamcollect.sh
cops_mailer_maillogs_keep: 700
cops_mailer_spamlearn_minutes: "{{60*48}}"
cops_mailer_spamlearn_periodicity: "* */1 * * *"
cops_mailer_maillogsize: 5242880
cops_mailer_spamcollect_user: spamcollect
cops_mailer_spamcollect_path: /data/spamcollect
cops_mailer_spamcollect_host: mail.mydomain.com
cops_mailer_reject_unlisted_recipient: ""
cops_mailer_website: "https://{{cops_mailer_hostname}}"
cops_mailer_sitename: antispam
cops_mailer_dmarc_rua: admin
cops_mailer_dmarc_ruf: admin
cops_mailer_message_size_limit: "210240000"
cops_mailer_relaynets: ""
cops_mailer_relayhost: ""
cops_mailer_webmail: rainloop
cops_mailer_ratelimit: "100/minute;10000/hour"
cops_mailer_tls_flavor: "letsencrypt"
cops_mailer_postmaster: admin
cops_mailer_mailu_version: "1.6"
cops_mailer_secret_key: supersecret123456789
cops_mailer_out_ips: ["{{ansible_default_ipv4.address}}"]
cops_mailer_out_ip: "{{cops_mailer_out_ips[0]}}"
cops_mailer_disable_statistics: "true"
cops_mailer_enable_admin: "true"
cops_mailer_dav: radicale
cops_mailer_antivirus: clamav
cops_mailer_real_ip_header: ""
cops_mailer_real_ip_from: ""
cops_mailer_subnet_prefix: 192.168.20
cops_mailer_subnet: "{{cops_mailer_subnet_prefix}}.0"
cops_mailer_subnet_mask: 24
cops_mailer_subnetp: "{{cops_mailer_subnet}}/{{cops_mailer_subnet_mask}}"
cops_mailer_rspamd_lua_dkim_networks: |-
  0.0.0.0/0
cops_mailer_rspamd_greylist_actions_reject: "50"
cops_mailer_rspamd_greylist_actions_add_header: "5.8"
cops_mailer_rspamd_greylist_actions_greylist: "4"
cops_mailer_rspamd_greylist_actions:
  reject: "{{cops_mailer_rspamd_greylist_actions_reject}}"
  add_header: "{{cops_mailer_rspamd_greylist_actions_add_header}}"
  greylist: "{{cops_mailer_rspamd_greylist_actions_greylist}}"
cops_mailer_rspamd_greylist_enable: "false"
cops_mailer_rspamd_regex_maxsize: "100000000"
cops_mailer_rspamd_lua_custom: ""
cops_mailer_rspamd_lua_whitelisted:
- "/@supezrfoorbar123879.com/im{all_header}"
cops_mailer_postfix_virtual_alias_map: ""
cops_mailer_postfix_transport_map: ""
cops_mailer_postfix_sender_transport_map: ""
cops_mailer_postfix_relay_domains_map: ""
cops_mailer_postfix_recipient_canonical_map: ""
cops_mailer_postfix_recipient_access_map: ""
cops_mailer_postfix_mynetworks_map: ""
cops_mailer_postfix_esmtp_access_default: |-
  0.0.0.0/0           silent-discard, dsn
  ::/0                silent-discard, dsn
cops_mailer_postfix_esmtp_access: |-
  {{cops_mailer_postfix_esmtp_access_default}}
cops_mailer_postfix_smtp_header_checks_map: |-
  /^\s*Authentication-Results:/ IGNORE
  /^\s*Authentication-Results-Original:/ IGNORE
  /^\s*x-rspamd-server:/               IGNORE
  /^\s*x-rspamd-queue-id:/             IGNORE
  /^\s*x-spamd-result:/                IGNORE
  /^\s*x-originating-ip:/              IGNORE
  /^\s*received:/                      IGNORE
  /^\s*user-agent:/                    IGNORE
  /^\s*x-sender:/                      IGNORE
  /^\s*x-enigmail:/                    IGNORE
  /^\s*x-mailer:/                      IGNORE
  /^\s*x-pgp-agent:/                   IGNORE
  /^\s*(mime-version:\s*[0-9\.]+)\s.+/ REPLACE $1
cops_mailer_postmaster: "postmaster@{{cops_mailer_tld_domain}}"
cops_mailer_postfix_milter_header_checks_map: |-
  /^X-Outgoing-Spam:\s+(yes|y|1)/ REDIRECT {{cops_mailer_postmaster.replace('@', '+outspam@')}}
  /^x-spam(-flag)?:\s+(yes|y|1)/ BCC {{cops_mailer_postmaster}}
  {{cops_mailer_postfix_header_checks_map}}
cops_mailer_postfix_header_checks_map: |-
  {{cops_mailer_postfix_smtp_header_checks_map}}
cops_mailer_postfix_blackout_map: ""
cops_mailer_rspamd_testspam_token: "a7F7S2Pk1731rwe"
cops_mailer_rspamd_milter_skip_local: "false"
cops_mailer_rspamd_milter_skip_authenticated: "false"
cops_mailer_rspamd_milter_remove_upstream_spam_flag: "true"
cops_mailer_rspamd_milter_extended_headers_rcpt: ''
cops_mailer_rspamd_milter_use: '[]'
# cops_mailer_rspamd_milter_use: '["x-spamd-bar", "x-spam-level", "x-virus"]'
cops_mailer_rspamd_milter_extended_spam_headers: 'false'
cops_mailer_rspamd_milter_authenticated_headers: "{{cops_mailer_rspamd_milter_use}}"
cops_mailer_rspamd_milter_local_headers: "{{cops_mailer_rspamd_milter_use}}"
cops_mailer_rspamd_milter_extra: ''
cops_mailer_rspamd_regex_extra: ''
cops_mailer_rspamd_redis_extra: ''
cops_mailer_rspamd_greylist_extra: ''
cops_mailer_rspamd_actions_extra: ''
